# Generated by Django 2.2.7 on 2020-09-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numbering', models.BigIntegerField(verbose_name='编号')),
                ('applicationTime', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('theTerm', models.DateField(verbose_name='使用期限')),
                ('finish', models.BooleanField(default=False, verbose_name='订单状态')),
                ('Remarks', models.TextField(verbose_name='备注')),
                ('companyName', models.CharField(max_length=20, verbose_name='所在单位')),
                ('departmentName', models.CharField(max_length=30, verbose_name='所在部门')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('telephoneNumber', models.BigIntegerField(null=True, verbose_name='电话号码')),
                ('phoneNumber', models.BigIntegerField(null=True, verbose_name='手机号码')),
                ('mail', models.EmailField(max_length=254, verbose_name='邮箱地址')),
                ('Type', models.CharField(max_length=2, verbose_name='资源类型')),
                ('otherDevices', models.CharField(max_length=2, verbose_name='其他设备')),
                ('typeRemark', models.CharField(max_length=50, null=True, verbose_name='资源类型备注')),
                ('DevicesRemark', models.CharField(max_length=50, null=True, verbose_name='网络设备备注')),
            ],
        ),
    ]
