# Generated by Django 2.2.7 on 2020-09-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationApp', '0002_backstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backstage',
            name='link',
        ),
    ]
