# Generated by Django 2.2.7 on 2020-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationApp', '0003_remove_backstage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='filesname',
            field=models.FileField(upload_to='', verbose_name='文件上传'),
        ),
    ]
